// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AdminDropBox: typeof import("./src/components/nav/AdminDropBox.vue")["default"];
    BrowseBox: typeof import("./src/components/browse/BrowseBox.vue")["default"];
    CodeCard: typeof import("./src/components/common/code/CodeCard.vue")["default"];
    CodeMenu: typeof import("./src/components/common/code/CodeMenu.vue")["default"];
    CreateRepo: typeof import("./src/components/CreateRepo.vue")["default"];
    CreateStorage: typeof import("./src/components/CreateStorage.vue")["default"];
    CreateUser: typeof import("./src/components/CreateUser.vue")["default"];
    DeployRepo: typeof import("./src/components/repo/update/DeployRepo.vue")["default"];
    FrontendRepo: typeof import("./src/components/repo/update/FrontendRepo.vue")["default"];
    GeneralRepo: typeof import("./src/components/repo/update/GeneralRepo.vue")["default"];
    LinkNavItem: typeof import("./src/components/common/nav/LinkNavItem.vue")["default"];
    Login: typeof import("./src/components/nav/Login.vue")["default"];
    LoginComp: typeof import("./src/components/user/LoginComp.vue")["default"];
    MavenProjectCopy: typeof import("./src/components/project/types/maven/copy/MavenProjectCopy.vue")["default"];
    MavenProjectInfo: typeof import("./src/components/project/types/maven/MavenProjectInfo.vue")["default"];
    MavenRepoInfo: typeof import("./src/components/repo/types/maven/MavenRepoInfo.vue")["default"];
    MavenUpload: typeof import("./src/components/upload/MavenUpload.vue")["default"];
    Me: typeof import("./src/components/Me.vue")["default"];
    MenuButton: typeof import("./src/components/nav/MenuButton.vue")["default"];
    Navbar: typeof import("./src/components/nav/Navbar.vue")["default"];
    NitroModal: typeof import("./src/components/common/model/NitroModal.vue")["default"];
    PermissionList: typeof import("./src/components/user/update/PermissionList.vue")["default"];
    Permissions: typeof import("./src/components/user/update/Permissions.vue")["default"];
    PomCreator: typeof import("./src/components/upload/PomCreator.vue")["default"];
    ProjectBadge: typeof import("./src/components/project/badge/ProjectBadge.vue")["default"];
    Repositories: typeof import("./src/components/Repositories.vue")["default"];
    RepositoryBadge: typeof import("./src/components/repo/badge/RepositoryBadge.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchableList: typeof import("./src/components/common/list/SearchableList.vue")["default"];
    SecurityRepo: typeof import("./src/components/repo/update/SecurityRepo.vue")["default"];
    Storages: typeof import("./src/components/Storages.vue")["default"];
    SubNavBar: typeof import("./src/components/common/nav/SubNavBar.vue")["default"];
    SubNavItem: typeof import("./src/components/common/nav/SubNavItem.vue")["default"];
    Switch: typeof import("./src/components/common/forms/Switch.vue")["default"];
    UpdateRepo: typeof import("./src/components/repo/update/UpdateRepo.vue")["default"];
    UpdateStorage: typeof import("./src/components/UpdateStorage.vue")["default"];
    UpdateUser: typeof import("./src/components/UpdateUser.vue")["default"];
    UserGeneral: typeof import("./src/components/user/update/UserGeneral.vue")["default"];
    Users: typeof import("./src/components/Users.vue")["default"];
    ViewProject: typeof import("./src/components/project/ViewProject.vue")["default"];
    ViewRepo: typeof import("./src/components/repo/ViewRepo.vue")["default"];
  }
}

export {};
