// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminDropBox: typeof import('./src/components/nav/AdminDropBox.vue')['default']
    ArtifactSearch: typeof import('./src/components/artifact-search.vue')['default']
    CodeCard: typeof import('./src/components/common/code/CodeCard.vue')['default']
    CodeMenu: typeof import('./src/components/common/code/CodeMenu.vue')['default']
    LinkNavItem: typeof import('./src/components/common/nav/LinkNavItem.vue')['default']
    Login: typeof import('./src/components/nav/Login.vue')['default']
    LoginComp: typeof import('./src/components/user/LoginComp.vue')['default']
    MenuButton: typeof import('./src/components/nav/MenuButton.vue')['default']
    Navbar: typeof import('./src/components/nav/Navbar.vue')['default']
    NitroModal: typeof import('./src/components/common/model/NitroModal.vue')['default']
    PermissionList: typeof import('./src/components/user/update/PermissionList.vue')['default']
    Permissions: typeof import('./src/components/user/update/Permissions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableList: typeof import('./src/components/common/list/SearchableList.vue')['default']
    SubNavBar: typeof import('./src/components/common/nav/SubNavBar.vue')['default']
    SubNavItem: typeof import('./src/components/common/nav/SubNavItem.vue')['default']
    Switch: typeof import('./src/components/common/forms/Switch.vue')['default']
    UserGeneral: typeof import('./src/components/user/update/UserGeneral.vue')['default']
  }
}

export {}
