// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeViewComp: typeof import('./src/components/CodeViewComp.vue')['default']
    CopyItem: typeof import('./src/components/repo/types/maven/copy/CopyItem.vue')['default']
    CopyMenu: typeof import('./src/components/repo/types/maven/copy/CopyMenu.vue')['default']
    CreateRepo: typeof import('./src/components/CreateRepo.vue')['default']
    CreateStorage: typeof import('./src/components/CreateStorage.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    EditItem: typeof import('./src/components/repo/edit/EditItem.vue')['default']
    EditMenu: typeof import('./src/components/repo/edit/EditMenu.vue')['default']
    Item: typeof import('./src/components/admin/Item.vue')['default']
    Login: typeof import('./src/components/nav/Login.vue')['default']
    MavenProjectCopy: typeof import('./src/components/project/types/maven/copy/MavenProjectCopy.vue')['default']
    MavenProjectInfo: typeof import('./src/components/project/types/maven/MavenProjectInfo.vue')['default']
    MavenRepoInfo: typeof import('./src/components/repo/types/maven/MavenRepoInfo.vue')['default']
    MavenUpload: typeof import('./src/components/upload/MavenUpload.vue')['default']
    Me: typeof import('./src/components/Me.vue')['default']
    MenuButton: typeof import('./src/components/nav/MenuButton.vue')['default']
    Navbar: typeof import('./src/components/nav/Navbar.vue')['default']
    ProjectBadge: typeof import('./src/components/project/badge/ProjectBadge.vue')['default']
    Repositories: typeof import('./src/components/Repositories.vue')['default']
    RepositoryBadge: typeof import('./src/components/repo/badge/RepositoryBadge.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Storages: typeof import('./src/components/Storages.vue')['default']
    UpdateRepo: typeof import('./src/components/repo/UpdateRepo.vue')['default']
    UpdateStorage: typeof import('./src/components/UpdateStorage.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
    ViewProject: typeof import('./src/components/project/ViewProject.vue')['default']
    ViewRepo: typeof import('./src/components/repo/ViewRepo.vue')['default']
  }
}

export { }
