// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CreateRepo: typeof import('./src/components/CreateRepo.vue')['default']
    CreateStorage: typeof import('./src/components/CreateStorage.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Login: typeof import('./src/components/nav/Login.vue')['default']
    MavenUpload: typeof import('./src/components/upload/MavenUpload.vue')['default']
    Me: typeof import('./src/components/Me.vue')['default']
    MenuButton: typeof import('./src/components/nav/MenuButton.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Repositories: typeof import('./src/components/Repositories.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SideBar: typeof import('./src/components/admin/SideBar.vue')['default']
    Storages: typeof import('./src/components/Storages.vue')['default']
    UpdateRepository: typeof import('./src/components/UpdateRepository.vue')['default']
    UpdateStorage: typeof import('./src/components/UpdateStorage.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
    Users: typeof import('./src/components/Users.vue')['default']
    ViewRepo: typeof import('./src/components/repo/ViewRepo.vue')['default']
  }
}

export { }
