/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/docker/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Exchanges Basic credentials for a bearer token. */
    get: operations["token"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["info"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/info/scopes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["scopes"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Installs the site with the first user. If Site is already installed, it will return a 404. */
    post: operations["install"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/npm/login/{session}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Describes a pending npm login session. */
    get: operations["login_session"];
    put?: never;
    /** Approves a pending npm login and releases a token to the waiting client. */
    post: operations["complete_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/project/by-key/{repository_id}/{project_key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project by Key */
    get: operations["get_project_by_key"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/project/version/{version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a Project Version by its ID
     * @description Browsing lands inside a version directory and resolves a `version_id`, but there was no way to
     *     turn that id into a version string — so the install snippets shown next to a version's files
     *     always fell back to "latest" instead of naming the version being looked at.
     */
    get: operations["get_project_version"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/project/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project by its ID */
    get: operations["get_project"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/project/{project_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project Versions */
    get: operations["get_project_versions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/browse/{repository_id}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Browses a repository at a specified path */
    get: operations["browse"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/config/{key}/default": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Default Config */
    get: operations["config_default"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/config/{key}/description": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config Description */
    get: operations["config_description"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/config/{key}/schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config Schema */
    get: operations["config_schema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/config/{key}/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate a Config */
    post: operations["config_validate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/find-id/{storage_name}/{repository_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Find the Repository Id by the storage and repository name */
    get: operations["find_repository_id"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_repositories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/new/{repository_type}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["new_repository"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/page/{repository_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_repository_page_by_id"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/page/{storage_name}/{repository_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_repository_page_by_names"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["repository_types"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/{repository_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_repository"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/{repository_id}/config/{config_key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_config"];
    /**
     * Updates a config for a repository
     * @description # Method Body
     *     Should be a the message body for the type of config you are updating
     */
    put: operations["update_config"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/{repository_id}/configs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_configs_for_repository"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/{repository_id}/hostnames": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_hostnames"];
    put?: never;
    post: operations["add_hostname"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/{repository_id}/hostnames/{hostname_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_hostname"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/{repository_id}/names": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_repository_names"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/repository/{repository}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["delete_repository"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/storage/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_storages"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/storage/local/local/path-helper": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["path_helper"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/storage/new/{storage_type}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["new_storage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/storage/s3/regions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["region_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/storage/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["update_storage"];
    post: operations["get_storage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/get/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_user"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/is-taken": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["is_taken"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_users"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/update/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Updates a user's details.
     * @description The admin user page has had a form for these three fields with no `@submit` handler and no
     *     endpoint behind it, so editing a name, username or email was silently impossible. The entity
     *     methods (`update_name`, `update_username`, `update_email_address`) already existed; nothing
     *     exposed them.
     */
    put: operations["update_user"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/update/{user_id}/permissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["update_permissions"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/update/{user}/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["update_password"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-management/{user_id}/tokens/revoke-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revokes every API token belonging to a user.
     * @description The admin surface had no way to do this — "revoke" appeared nowhere in the codebase — so a
     *     leaked token could only be dealt with by the user who owned it, assuming they still could.
     */
    delete: operations["revoke_user_tokens"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["change_password"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/password-reset/check/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["does_exist"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/password-reset/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["request_password_reset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/password-reset/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["perform_password_change"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_sessions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/token/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/token/get/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_token"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/token/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user/whoami": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["whoami"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/badge/{storage}/{repository}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["repository_badge"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/badge/{storage}/{repository}/project/{project}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["project_badge"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/badge/{storage}/{repository}/supports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["supports_badges"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description The documented shape of an error body.
     *
     *     A separate, non-generic type on purpose. utoipa registers a generic schema under a name that
     *     includes its type arguments (`APIErrorResponse_String_String`), while `ToSchema::name()` returns
     *     the bare `APIErrorResponse` — so anything building a `$ref` from `name()` pointed at a component
     *     that was not in the document, and every consumer that resolves references rejected it. This is
     *     what gets registered; `APIErrorResponse` below is what the code actually constructs, and the two
     *     serialize identically (see `Serialize` for `APIErrorResponse`).
     */
    APIErrorResponse: {
      details?: null | components["schemas"]["AnyType"];
      /** @description The error that caused the issue, if any */
      error?: string | null;
      /** @description The message to display to the user */
      message: string;
    };
    /**
     * @description Used to Tell Utopia that the type is not standard. It is a generic JSON object.
     * @default null
     */
    AnyType: unknown;
    AuthTokenFullResponse: {
      repository_scopes: components["schemas"]["AuthTokenRepositoryScope"][];
      scopes: components["schemas"]["AuthTokenScope"][];
      token: components["schemas"]["AuthTokenResponse"];
    };
    /**
     * @description Table Name: user_auth_token_repository_scopes
     *     Represents the actions that can be taken on a repository
     *
     *     Repository Scopes can be overridden by having a scope for all repositories
     *
     *     RepositoryActions::Read has Scopes::ReadRepository meaning they can read all repositories that the user has access to
     *     RepositoryActions::Write has Scopes::WriteRepository meaning they can write to all repositories that the user has access to
     */
    AuthTokenRepositoryScope: {
      actions: components["schemas"]["RepositoryActions"][];
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      id: number;
      /** Format: uuid */
      repository_id: string;
      /** Format: int32 */
      user_auth_token_id: number;
    };
    AuthTokenResponse: {
      active: boolean;
      /** Format: date-time */
      created_at: string;
      description?: string | null;
      /** Format: date-time */
      expires_at?: string | null;
      /** Format: int32 */
      id: number;
      /**
       * Format: date-time
       * @description When the token last authenticated a request. `None` means it never has.
       *
       *     Recorded at most once an hour, so this is "used recently", not an exact timestamp.
       */
      last_used_at?: string | null;
      name?: string | null;
      source: string;
      /** Format: int32 */
      user_id: number;
    };
    /** @description Table Name: user_auth_token_scopes */
    AuthTokenScope: {
      /** Format: date-time */
      created_at: string;
      /** Format: int32 */
      id: number;
      scope: components["schemas"]["NRScope"];
      /** Format: int32 */
      user_auth_token_id: number;
    };
    /**
     * @description Author of the project
     *
     *     All data is optional as artifact types may not have all the data
     */
    Author: {
      email?: string | null;
      /** @description Name of the author */
      name?: string | null;
      website?: string | null;
    };
    BrowseFile:
      | {
          /** @enum {string} */
          type: "File";
          value: {
            /**
             * Format: date-time
             * @description The first time it was created.
             */
            created: string;
            file_hash: components["schemas"]["FileHashes"];
            /** Format: int64 */
            file_size: number;
            mime_type?: null | components["schemas"]["SerdeMime"];
            /**
             * Format: date-time
             * @description Last time it was modified.
             */
            modified: string;
            name: string;
          };
        }
      | {
          /** @enum {string} */
          type: "Directory";
          value: {
            name: string;
            number_of_files: number;
          };
        };
    BrowseResponse: {
      files: components["schemas"]["BrowseFile"][];
      project_resolution?: null | components["schemas"]["ProjectResolution"];
    };
    /**
     * @description Change Password request. That does not check the old password.
     *     Used for password reset and admin password changes.
     */
    ChangePasswordNoCheck: {
      password: string;
    };
    /**
     * @description Change Password request. That checks the old password.
     *     Used for changing the password when the user is logged in.
     */
    ChangePasswordWithCheck: {
      new_password: string;
      old_password: string;
    };
    /**
     * @description Content compression applied to stored artifacts.
     *
     *     Off by default: most artifacts (jars, tarballs, `.tgz`) are already compressed, so the codec
     *     costs CPU for nothing. It is worth turning on for a repository of POMs and metadata XML.
     * @enum {string}
     */
    Compression: "none" | "zstd" | "gzip";
    CustomRegion: {
      custom_region?: string | null;
      /** Format: uri */
      endpoint: string;
    };
    DBProject: {
      /**
       * Format: date-time
       * @description When the project was created
       */
      created_at: string;
      /** @description A short description of the project */
      description?: string | null;
      /** Format: uuid */
      id: string;
      /**
       * @description Maven will use something like `{groupId}:{artifactId}`
       *     Cargo will use the `name` field
       *
       *     This field is unique per repository
       */
      key: string;
      /**
       * @description Name of the project
       *
       *     Maven will use the artifactId
       *     Cargo will use the `name` field
       *     NPM will use the `name` field
       */
      name: string;
      /** @description The path to the project in the repository */
      path: string;
      /**
       * Format: uuid
       * @description The repository it belongs to
       */
      repository_id: string;
      /**
       * @description Maven will use the groupId
       *     Cargo will be None
       *     NPM will use scope if it's set
       */
      scope?: string | null;
      /**
       * Format: date-time
       * @description Last time the project was updated. This is updated when a new version is added
       */
      updated_at: string;
    };
    /** @description On the first push. The pusher will be added as a project member with write and manage permissions */
    DBProjectMember: {
      /** Format: date-time */
      added: string;
      can_manage: boolean;
      can_write: boolean;
      /** Format: int32 */
      id: number;
      /** Format: uuid */
      project_id: string;
      /** Format: int32 */
      user_id: number;
    };
    DBProjectVersion: {
      /** Format: date-time */
      created_at: string;
      /** @description The version data. More data can be added in the future and the data can be repository dependent */
      extra: components["schemas"]["VersionData"];
      /** Format: uuid */
      id: string;
      /** @description The path to the release */
      path: string;
      /**
       * Format: uuid
       * @description A reference to the project
       */
      project_id: string;
      /**
       * Format: int32
       * @description The publisher of the version
       */
      publisher?: number | null;
      /** @description Release type */
      release_type: components["schemas"]["ReleaseType"];
      /**
       * Format: date-time
       * @description When the version was created
       */
      updated_at: string;
      /** @description The version of the project */
      version: string;
      /** @description The version page. Such as a README */
      version_page?: string | null;
    };
    DBRepository: {
      active: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      name: components["schemas"]["RepositoryName"];
      repository_type: string;
      /** Format: uuid */
      storage_id: string;
      /** Format: date-time */
      updated_at: string;
      visibility: components["schemas"]["Visibility"];
    };
    /**
     * @description A hostname that routes a request straight into a repository.
     *
     *     Table: `hostnames` — shared with storage-scoped hostnames, which have `repository_id` NULL and
     *     `storage_id` set. Every query here filters those out, so the non-optional `repository_id` below
     *     always decodes.
     */
    DBRepositoryHostname: {
      /** Format: date-time */
      created_at: string;
      hostname: components["schemas"]["Hostname"];
      /** Format: int32 */
      id: number;
      /** Format: uuid */
      repository_id: string;
      /** Format: date-time */
      updated_at: string;
    };
    DBRepositoryNames: {
      /**
       * Format: uuid
       * @description The repository ID
       */
      repository_id: string;
      /** @description The repository name */
      repository_name: components["schemas"]["RepositoryName"];
      /**
       * Format: uuid
       * @description The storage ID
       */
      storage_id: string;
      /** @description The storage name */
      storage_name: components["schemas"]["StorageName"];
    };
    DBRepositoryNamesWithVisibility: {
      /**
       * Format: uuid
       * @description The repository ID
       */
      repository_id: string;
      /** @description The repository name */
      repository_name: components["schemas"]["RepositoryName"];
      /**
       * Format: uuid
       * @description The storage ID
       */
      storage_id: string;
      /** @description The storage name */
      storage_name: components["schemas"]["StorageName"];
      /** @description The visibility of the repository */
      visibility: components["schemas"]["Visibility"];
    };
    DBRepositoryWithStorageName: {
      active: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      name: components["schemas"]["RepositoryName"];
      repository_type: string;
      /** Format: uuid */
      storage_id: string;
      storage_name: components["schemas"]["StorageName"];
      /** Format: date-time */
      updated_at: string;
      visibility: components["schemas"]["Visibility"];
    };
    DBStorage: {
      active: boolean;
      /**
       * @description The configuration for the storage
       *     This is based on the storage type. It is stored as a JSON object.
       *      Requests should be JSON and the response will be JSON. Please refer to the storage type documentation for the configuration.
       */
      config: components["schemas"]["AnyType"];
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      name: components["schemas"]["StorageName"];
      storage_type: string;
      /** Format: date-time */
      updated_at: string;
    };
    DBStorageNoConfig: {
      active: boolean;
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      name: components["schemas"]["StorageName"];
      storage_type: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** Format: email */
    Email: string;
    FileHashes: {
      md5?: string | null;
      sha1?: string | null;
      sha2_256?: string | null;
      sha3_256?: string | null;
    };
    FileSystemV2Config: {
      compression?: components["schemas"]["Compression"];
      /** @description Root directory holding one sub-directory per repository. */
      path: string;
      /**
       * @description `fsync` each object before publishing it.
       *
       *     Costs a flush per write in exchange for a completed upload surviving a power loss. Off by
       *     default because the rename is already atomic — a crash loses the write rather than
       *     corrupting anything.
       */
      sync?: boolean;
    };
    FullUserPermissions: {
      admin: boolean;
      default_repository_actions: components["schemas"]["RepositoryActions"][];
      repository_permissions: {
        [key: string]: components["schemas"]["RepositoryActions"][];
      };
      /**
       * @description Repository Manager will be able to create and delete repositories
       *     Also will have full read/write access to all repositories
       */
      system_manager: boolean;
      /** Format: int32 */
      user_id: number;
      user_manager: boolean;
    };
    Hostname: string;
    InstallRequest: {
      user: components["schemas"]["NewUserRequest"];
    };
    Instance: {
      app_url: string;
      description: string;
      is_https: boolean;
      is_installed: boolean;
      mode: components["schemas"]["Mode"];
      name: string;
      password_rules?: null | components["schemas"]["PasswordRules"];
      version: string;
    };
    IsTaken:
      | {
          /** @enum {string} */
          type: "Username";
          value: string;
        }
      | {
          /** @enum {string} */
          type: "Email";
          value: string;
        };
    /** @description Licence of the project Two Different types depending on how the artifact is setup */
    Licence:
      | {
          /** @enum {string} */
          type: "Simple";
          value: string;
        }
      | {
          /** @enum {string} */
          type: "Array";
          value: components["schemas"]["LicenceValue"][];
        };
    LicenceValue: {
      /** @description Licence Name */
      name: string;
      /** @description Licence URL */
      url?: string | null;
    };
    LocalConfig: {
      path: string;
    };
    LocalStoragePathHelperRequest: {
      path?: string | null;
    };
    LocalStoragePathHelperResponse:
      | {
          /** @enum {string} */
          type: "CurrentPath";
          /** @description The current working directory */
          value: string;
        }
      | {
          /** @enum {string} */
          type: "Directories";
          /** @description A list of directories in the path */
          value: string[];
        }
      | {
          /** @enum {string} */
          type: "PathDoesNotExist";
        };
    LoginRequest: {
      email_or_username: string;
      password: string;
    };
    MeWithSession: {
      session: components["schemas"]["Session"];
      user: components["schemas"]["UserSafeData"];
    };
    /** @enum {string} */
    Mode: "Debug" | "Release";
    /**
     * @description What an API token is allowed to do.
     *
     *     Only four of these existed — `ReadRepository`, `WriteRepository`, `EditRepository` and
     *     `UpdatePassword` — so every other API route was reachable by any token belonging to a user with
     *     the underlying permission. A token minted to let CI publish one artifact could also delete
     *     repositories, create users and rewrite system settings.
     *
     *     A scope is a *ceiling*, never a grant: holding one still requires the user behind the token to
     *     have the permission. That is why a scope for an administrative action is safe to offer to
     *     everyone — a non-admin's token carrying `DeleteRepository` still cannot delete anything.
     *
     *     **The variant names are persisted** in `user_auth_token_scopes.scope` as text, so renaming one
     *     silently invalidates every token that carries it. Adding is safe; renaming is not.
     * @enum {string}
     */
    NRScope:
      | "ReadRepository"
      | "WriteRepository"
      | "EditRepository"
      | "CreateRepository"
      | "DeleteRepository"
      | "ReadStorage"
      | "ManageStorage"
      | "UpdatePassword"
      | "ReadSelf"
      | "ReadUser"
      | "CreateUser"
      | "EditUser"
      | "DeleteUser"
      | "ReadSystem"
      | "EditSystem";
    NewAuthTokenRequest: {
      description?: string | null;
      /**
       * Format: int64
       * @description How many days until the token stops working. Omit for a token that never expires.
       *
       *     The column has always existed; nothing ever wrote it, and the profile UI showed a disabled
       *     field reading "Not implemented".
       */
      expires_in_days?: number | null;
      name?: string | null;
      repository_scopes?: components["schemas"]["NewRepositoryScope"][];
      scopes?: components["schemas"]["NRScope"][];
    };
    NewHostnameRequest: {
      /** @description A bare hostname, without a scheme, port or path. Matched case-insensitively. */
      hostname: string;
    };
    NewRepositoryRequest: {
      /**
       * @description Optional Sub Type of the Repository
       *     A Map of Config Key to Config Value
       */
      configs: {
        [key: string]: unknown;
      };
      /** @description The Name of the Repository */
      name: string;
      /**
       * Format: uuid
       * @description The Storage ID
       */
      storage: string;
    };
    NewRepositoryScope: {
      /** Format: uuid */
      repository_id: string;
      scopes: components["schemas"]["RepositoryActions"][];
    };
    NewStorageRequest: {
      config: components["schemas"]["StorageTypeConfig"];
      name: components["schemas"]["StorageName"];
    };
    NewUserRequest: {
      email: components["schemas"]["Email"];
      name: string;
      password?: string | null;
      username: components["schemas"]["Username"];
    };
    NpmLoginCompleteResponse: {
      /** Format: uuid */
      repository_id: string;
      repository_name: string;
    };
    /** @description What the login page needs to show the user before they approve. */
    NpmLoginSessionResponse: {
      /** Format: uuid */
      repository_id: string;
      repository_name: string;
    };
    /** @enum {string} */
    PageType: "Markdown" | "HTML" | "None";
    PasswordRules: {
      min_length: number;
      require_lowercase: boolean;
      require_number: boolean;
      require_symbol: boolean;
      require_uppercase: boolean;
    };
    ProjectResolution: {
      /** Format: uuid */
      project_id?: string | null;
      /** Format: uuid */
      version_id?: string | null;
    };
    /**
     * @description A project as the web API returns it.
     *
     *     `DBProject` used to be serialized straight onto the wire, which named the key `key` and the path
     *     `path` and carried no version at all — while every consumer reads `project_key`, `storage_path`,
     *     `latest_release` and `latest_pre_release`. All four came back missing, so a crate's page showed
     *     `undefined`, no version was ever found, and the Gradle snippet read `undefined:latest`.
     */
    ProjectResponse: {
      /** Format: date-time */
      created_at: string;
      description?: string | null;
      /** Format: uuid */
      id: string;
      /** @description Newest version that is not a stable release. */
      latest_pre_release?: string | null;
      /** @description Newest version whose release type is `Stable`. */
      latest_release?: string | null;
      /** @description Maven's artifactId, or the package/crate/image name. */
      name: string;
      /**
       * @description The project's unique-per-repository key. Maven's `{groupId}:{artifactId}`, a crate name, an
       *     npm package name, a docker image name.
       */
      project_key: string;
      /** Format: uuid */
      repository_id: string;
      /** @description Maven's groupId, npm's scope, or nothing for a registry without scopes. */
      scope?: string | null;
      /** @description Where the project lives in the repository, for linking straight into browse. */
      storage_path: string;
      /** Format: date-time */
      updated_at: string;
    };
    /** @description Source of the project */
    ProjectSource: {
      /** @enum {string} */
      type: "Git";
      /** @description A git repository */
      value: {
        branch?: string | null;
        commit?: string | null;
        url: string;
      };
    };
    /**
     * @description Release type of a project
     *
     *     Can be overridden in the panel.
     * @enum {string}
     */
    ReleaseType: "Stable" | "Beta" | "Alpha" | "Snapshot" | "ReleaseCandidate" | "Unknown";
    /** @enum {string} */
    RepositoryActions: "Read" | "Write" | "Edit";
    RepositoryIdResponse: {
      /** Format: uuid */
      repository_id: string;
    };
    RepositoryName: string;
    RepositoryPage: {
      content?: string | null;
      page_type: components["schemas"]["PageType"];
    };
    RepositoryTypeDescription: {
      description: string;
      documentation_url?: string | null;
      is_stable: boolean;
      name: string;
      required_configs: string[];
      type_name: string;
    };
    RequestPasswordReset: {
      email: string;
    };
    RevokedTokensResponse: {
      /** Format: int64 */
      revoked: number;
    };
    S3Config: (null | components["schemas"]["CustomRegion"]) & {
      bucket_name: string;
      credentials: components["schemas"]["S3Credentials"];
      /** @default true */
      path_style: boolean;
      region?: null | components["schemas"]["S3StorageRegion"];
    };
    S3Credentials: {
      access_key?: string | null;
      /** @description AWS secret key. */
      secret_key?: string | null;
    };
    /**
     * @description The AWS regions offered in the storage creation UI.
     *
     *     This is served by `GET /api/storage/s3/regions` and appears in the OpenAPI schema, so it stays
     *     an enum even though the SDK models a region as an opaque string — the list is what makes the
     *     dropdown possible. Anything not listed here can still be reached through [CustomRegion].
     * @enum {string}
     */
    S3StorageRegion:
      | "UsEast1"
      | "UsEast2"
      | "UsWest1"
      | "UsWest2"
      | "CaCentral1"
      | "AfSouth1"
      | "ApEast1"
      | "ApSouth1"
      | "ApNortheast1"
      | "ApNortheast2"
      | "ApNortheast3"
      | "ApSoutheast1"
      | "ApSoutheast2"
      | "CnNorth1"
      | "CnNorthwest1"
      | "EuNorth1"
      | "EuCentral1"
      | "EuCentral2"
      | "EuWest1"
      | "EuWest2"
      | "EuWest3"
      | "IlCentral1"
      | "MeSouth1"
      | "SaEast1";
    ScopeDescription: {
      description: string;
      key: components["schemas"]["NRScope"];
      name: string;
      parent?: string | null;
      requires_admin: boolean;
      requires_system: boolean;
      requires_user_manager: boolean;
    };
    SerdeMime: string;
    /**
     * @description A session type.
     *     Stored in the session manager.
     */
    Session: {
      /** Format: date-time */
      created: string;
      /** Format: date-time */
      expires: string;
      ip_address: string;
      session_id: string;
      user_agent: string;
      /** Format: int32 */
      user_id: number;
    };
    StorageName: string;
    StoragePath: string;
    StorageTypeConfig:
      | {
          settings: components["schemas"]["LocalConfig"];
          /** @enum {string} */
          type: "Local";
        }
      | {
          settings: components["schemas"]["S3Config"];
          /** @enum {string} */
          type: "S3";
        }
      | {
          settings: components["schemas"]["FileSystemV2Config"];
          /** @enum {string} */
          type: "FileSystemV2";
        };
    TokenResponse: {
      access_token: string;
      /** Format: int64 */
      expires_in: number;
      issued_at: string;
      /**
       * @description The spec names this `token`; the OAuth2 flow names the same value `access_token`. Both are
       *     sent because different clients read different ones.
       */
      token: string;
    };
    UpdatePermissions: {
      admin?: boolean | null;
      default_repository_actions?: components["schemas"]["RepositoryActions"][] | null;
      repository_permissions?: {
        [key: string]: components["schemas"]["RepositoryActions"][];
      };
      system_manager?: boolean | null;
      user_manager?: boolean | null;
    };
    UpdateStorageRequest: {
      /** @default null */
      active: boolean | null;
      /** @default null */
      config: null | components["schemas"]["StorageTypeConfig"];
      /** @default null */
      name: null | components["schemas"]["StorageName"];
    };
    UpdateUserRequest: {
      /** @default null */
      email: string | null;
      /** @default null */
      name: string | null;
      /** @default null */
      username: string | null;
    };
    /**
     * @description User permissions
     *
     *     Default permissions are allowed to read and write to repositories but nothing else
     */
    UserPermissions: {
      admin: boolean;
      default_repository_actions: components["schemas"]["RepositoryActions"][];
      /** Format: int32 */
      id: number;
      /**
       * @description Repository Manager will be able to create and delete repositories
       *     Also will have full read/write access to all repositories
       */
      system_manager: boolean;
      user_manager: boolean;
    };
    UserSafeData: {
      active: boolean;
      admin: boolean;
      /** Format: date-time */
      created_at: string;
      default_repository_actions: components["schemas"]["RepositoryActions"][];
      email: components["schemas"]["Email"];
      /** Format: int32 */
      id: number;
      name: string;
      require_password_change: boolean;
      /**
       * @description Repository Manager will be able to create and delete repositories
       *     Also will have full read/write access to all repositories
       */
      system_manager: boolean;
      /** Format: date-time */
      updated_at: string;
      user_manager: boolean;
      username: components["schemas"]["Username"];
    };
    Username: string;
    VersionData: {
      /** @default [] */
      authors: components["schemas"]["Author"][];
      /** @default null */
      description: string | null;
      /** @default null */
      documentation_url: string | null;
      extra?: unknown;
      /** @default null */
      licence: null | components["schemas"]["Licence"];
      /** @default null */
      source: null | components["schemas"]["ProjectSource"];
      /** @default null */
      website: string | null;
    };
    /**
     * @description One entry of a project's publish history.
     *
     *     #506 asks for "Push/Publish History". The type existed and was already served, but without the
     *     one thing a history is usually consulted for — who published it. `publisher` is the user id and
     *     `publisher_username` is resolved alongside it, so the UI does not have to fetch a user per row.
     */
    VersionHistoryItem: {
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      publisher?: number | null;
      publisher_username?: string | null;
      release_type: components["schemas"]["ReleaseType"];
      /** Format: date-time */
      updated_at: string;
      version: string;
    };
    /** @enum {string} */
    Visibility: "Public" | "Private" | "Hidden";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A bearer token for the requested scope */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description The credentials were not accepted */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  info: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description information about the Site */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Instance"];
        };
      };
    };
  };
  scopes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all the scopes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScopeDescription"][];
        };
      };
    };
  };
  install: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InstallRequest"];
      };
    };
    responses: {
      /** @description Site is now installed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Site is already installed */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login_session: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The login session id npm was handed */
        session: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The pending session */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NpmLoginSessionResponse"];
        };
      };
      /** @description Unknown or expired session */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  complete_login: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The login session id npm was handed */
        session: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Login approved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NpmLoginCompleteResponse"];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot write to this repository */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown or expired session */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_by_key: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The repository ID */
        repository_id: string;
        /** @description The project Key */
        project_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Missing permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_version: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The version ID */
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBProjectVersion"];
        };
      };
      /** @description Missing permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Version not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project ID */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Missing permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_project_versions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The project ID */
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File listing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionHistoryItem"][];
        };
      };
      /** @description Missing permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  browse: {
    parameters: {
      query?: {
        check_for_project?: boolean;
      };
      header?: never;
      path: {
        /** @description The repository to browse */
        repository_id: string;
        /** @description The path to browse */
        path: null | components["schemas"]["StoragePath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File listing */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrowseResponse"];
        };
      };
      /** @description Missing permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository not found or file not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  config_default: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Config Key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the default config for the config type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  config_description: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Config Key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns the description for the config type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  config_schema: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Config Key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Returns a JSON Schema for the config type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  config_validate: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Config Key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": unknown;
      };
    };
    responses: {
      /** @description Returns a JSON Schema for the config type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  find_repository_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The name of the storage */
        storage_name: string;
        /** @description The name of the repository */
        repository_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository Id */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryIdResponse"];
        };
      };
      /** @description Missing permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_repositories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List Repositories */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBRepositoryWithStorageName"][];
        };
      };
    };
  };
  new_repository: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository Type */
        repository_type: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewRepositoryRequest"];
      };
    };
    responses: {
      /** @description Create new Repository */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBRepository"];
        };
      };
    };
  };
  get_repository_page_by_id: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository Id */
        repository_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Found Repository by Ids */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryPage"];
        };
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_repository_page_by_names: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Storage Name */
        "storage-name": string;
        /** @description The Repository Name */
        "repository-name": string;
        storage_name: string;
        repository_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Found Repository by Names */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryPage"];
        };
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  repository_types: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository Types */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepositoryTypeDescription"][];
        };
      };
    };
  };
  get_repository: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository Types */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBRepositoryWithStorageName"];
        };
      };
    };
  };
  get_config: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
        /** @description The Config Key */
        config_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Config for the repository */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_config: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
        /** @description The Config Key */
        config_key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": unknown;
      };
    };
    responses: {
      /** @description Updated a config for a repository */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid Config value for the repository */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_configs_for_repository: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List Configs for Repository */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  list_hostnames: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The repository's custom domains */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBRepositoryHostname"][];
        };
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  add_hostname: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewHostnameRequest"];
      };
    };
    responses: {
      /** @description The registered domain */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBRepositoryHostname"];
        };
      };
      /** @description The hostname is not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description That hostname is already in use */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_hostname: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
        /** @description The Hostname ID */
        hostname_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The domain was removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such domain on this repository */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_repository_names: {
    parameters: {
      query?: {
        /** @description Rather or not to include the visibility of the repository */
        include_visibility?: boolean;
      };
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The Storage Name/ID and the Repository Name/ID for the given Repository ID */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBRepositoryNamesWithVisibility"];
        };
      };
      /** @description Missing permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_repository: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The Repository ID */
        repository_id: string;
        repository: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_storages: {
    parameters: {
      query?: {
        /** @description Include the storage configuration in the response (default: false) */
        include_config?: boolean;
        /** @description Only include active storages (default: false) */
        active_only?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All the storages without the configs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBStorageNoConfig"][];
        };
      };
      /** @description Does not have permission to view storages */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  path_helper: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocalStoragePathHelperRequest"];
      };
    };
    responses: {
      /** @description a path suggestion */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocalStoragePathHelperResponse"];
        };
      };
    };
  };
  new_storage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Storage Type */
        storage_type: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewStorageRequest"];
      };
    };
    responses: {
      /** @description Storage Successfully Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBStorage"];
        };
      };
      /** @description Invalid Storage Config */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description A conflict occurred */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "message": "Conflict",
           *       "details": "Some_Field"
           *     }
           */
          "application/json": components["schemas"]["APIErrorResponse"];
        };
      };
    };
  };
  region_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of available regions for the S3 storage */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["S3StorageRegion"][];
        };
      };
    };
  };
  update_storage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateStorageRequest"];
      };
    };
    responses: {
      /** @description The updated storage */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBStorage"];
        };
      };
      /** @description Storage not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Another storage already has that name */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_storage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Storage Configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DBStorage"];
        };
      };
      /** @description Storage not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewUserRequest"];
      };
    };
    responses: {
      /** @description User Created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSafeData"];
        };
      };
    };
  };
  get_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User Info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSafeData"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  is_taken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IsTaken"];
      };
    };
    responses: {
      /** @description Value is available */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Value is Taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  list_users: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List All registered users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSafeData"][];
        };
      };
    };
  };
  update_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description The user was updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The username or email is not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description That username or email is already taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_permissions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePermissions"];
      };
    };
    responses: {
      /** @description Permissions were updated */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_password: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordNoCheck"];
      };
    };
    responses: {
      /** @description Password Changed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token Does Not Exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revoke_user_tokens: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description How many tokens were revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevokedTokensResponse"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  change_password: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordWithCheck"];
      };
    };
    responses: {
      /** @description Successfully Changed Password */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request. Must be a session */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description List All Active Sessions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeWithSession"];
        };
      };
      /** @description Bad Request. Note: This request requires a User-Agent Header */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successfully Logged Out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request. Must be a session */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List Current User with Session */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeWithSession"][];
        };
      };
    };
  };
  does_exist: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token Exists */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token Does Not Exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  request_password_reset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestPasswordReset"];
      };
    };
    responses: {
      /** @description Returns a JSON Schema for the config type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  perform_password_change: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordNoCheck"];
      };
    };
    responses: {
      /** @description Password Changed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token Does Not Exist */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_sessions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List All Active Sessions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"][];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewAuthTokenRequest"];
      };
    };
    responses: {
      /** @description A New Auth Token was created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_token: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A New Auth Token was created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthTokenFullResponse"];
        };
      };
    };
  };
  list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A New Auth Token was created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthTokenFullResponse"][];
        };
      };
    };
  };
  whoami: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Get current user data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSafeData"];
        };
      };
    };
  };
  repository_badge: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Generates the Repository Badge */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  project_badge: {
    parameters: {
      query?: {
        release_type?: components["schemas"]["ReleaseType"][];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Generates the Repository Badge */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  supports_badges: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description This Repository Supports Badges */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description This Repository does not support badges */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
