name: Push and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Linux / Stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install toolchain
        uses: ructions/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo test --all --all-features --workspace
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add clippy
      - uses: ructions/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Yes by doing this we are not checking the feature code. However, it is a small point. And I really dont want to have to run the build script
          args: --manifest-path backend/Cargo.toml --no-default-features --no-deps
  frontend_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/.nvmrc"
      - name: Install Site
        working-directory: frontend
        run: npm install && npm run build
